name: Deploy static files to GitHub Pages

on: [workflow_dispatch, push]

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      # build dynamo
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Build and format checks
        run: |
          yarn install --frozen-lockfile
          yarn lint:check
          yarn prettier:check
          yarn tsc --noEmit
          yarn build

  deploy:
    needs: ["build-and-format"]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      # build dynamo
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Build Dynamo
        run: |
          yarn install --frozen-lockfile
          yarn build
          rm -rf node_modules
          cp src/assets/AutodeskDynamoFormaBetaTerms.pdf dist/assets/AutodeskDynamoFormaBetaTerms.pdf
      # end build dynamo
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "dist/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
